name: 'Build and Install Cadius'
description: 'Builds and installs the Cadius tool for Apple II ProDOS disk images'
runs:
  using: "composite"
  steps:
    - run: >
        git clone https://github.com/mach-kernel/cadius /tmp/cadius &&
        make -C /tmp/cadius &&
        sudo make -C /tmp/cadius install
